
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/**.g.dart"
    - "**/**.gr.dart"
    - "**/**.freezed.dart"
    - "**/**.mocks.dart"

linter:
  rules:
    always_use_package_imports: true
    always_declare_return_types: true
    avoid_print: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
