const String emailErrorMsg = 'Not a valid email';
const String passwordErrorMsg = 'Not a valid password';
const String loginBtnTxt = 'Login';
const String logoutBtnTxt = 'Logout';
const String registerBtnTxt = 'No account?';
const String registerSubmitBtnTxt = 'Register';
const String passwordHint = 'Password';
const String emailHint = 'Email';
const String backBtnTxt = 'Back';
